# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=128)),
                ('cost_in_credits', models.BigIntegerField()),
                ('length', models.BigIntegerField()),
                ('max_atmosphering_speed', models.BigIntegerField()),
                ('cargo_capacity_kg', models.BigIntegerField()),
                ('hyperdrive_rating', models.IntegerField()),
                ('docking_station_latitide', models.FloatField()),
                ('docking_station_longitude', models.FloatField()),
            ],
        ),
    ]
