# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_auto_20160129_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='cargo_capacity_kg',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='cost_in_credits',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='docking_station_latitide',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='docking_station_longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='hyperdrive_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='length',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='manufacturer',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ship',
            name='max_atmosphering_speed',
            field=models.BigIntegerField(default=0),
        ),
    ]
