# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0003_auto_20160129_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='hyperdrive_rating',
            field=models.FloatField(default=0),
        ),
    ]
